package sqlutil;

import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

public class SqlQuery implements AutoCloseable {

    private final Connection connection;
    private PreparedStatement statement;
    private ResultSet result;

    public SqlQuery(Connection connection) {
        this.connection = connection;
    }

    public SqlQuery(Connection connection, boolean autoCommit) throws SQLException {
        this(connection);
        connection.setAutoCommit(autoCommit);
    }

    public SqlQuery(Connection connection, String sql) throws SQLException {
        this(connection);
        this.statement = connection.prepareStatement(sql);
    }

    public SqlQuery(Connection connection, boolean autoCommit, String sql) throws SQLException {
        this(connection, autoCommit);
        this.statement = connection.prepareStatement(sql);
    }

    public SqlQuery(Connection connection, String sql, int autoGeneratedKeys) throws SQLException {
        this(connection);
        this.statement = connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public SqlQuery(Connection connection, boolean autoCommit, String sql, int autoGeneratedKeys) throws SQLException {
        this(connection, autoCommit);
        this.statement = connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public SqlQuery(Connection connection, String sql, Param... params) throws SQLException {
        this(connection, sql);
        setParams(params);
    }

    public SqlQuery(Connection connection, boolean autoCommit, String sql, Param... params) throws SQLException {
        this(connection, autoCommit, sql);
        setParams(params);
    }

    public SqlQuery(Connection connection, String sql, int autoGeneratedKeys, Param... params) throws SQLException {
        this(connection, sql, autoGeneratedKeys);
        setParams(params);
    }

    public SqlQuery(Connection connection, boolean autoCommit, String sql, int autoGeneratedKeys, Param... params) throws SQLException {
        this(connection, autoCommit, sql, autoGeneratedKeys);
        setParams(params);
    }

    public Connection connection() {
        return connection;
    }

    public PreparedStatement statement() {
        return statement;
    }

    public void setStatement(PreparedStatement statement) throws SQLException {
        if (this.statement != null) this.statement.close();
        this.statement = statement;
    }

    public ResultSet result() {
        return result;
    }

    public void setResult(ResultSet result) throws SQLException {
        if (this.result != null) this.result.close();
        this.result = result;
    }

    public ResultSet fetch() throws SQLException {
        validateStatementNotNull();
        setResult(statement.executeQuery());
        return result;
    }

    public ResultSet fetchKeys() throws SQLException {
        validateStatementNotNull();
        statement.executeUpdate();
        setResult(statement.getGeneratedKeys());
        return result;
    }

    public long fetchKeyLong() throws SQLException {
        if (fetchKeys().next()) {
            return result.getLong(1);
        }
        throw noKeyException();
    }

    public int fetchKeyInt() throws SQLException {
        if (fetchKeys().next()) {
            return result.getInt(1);
        }
        throw noKeyException();
    }

    public short fetchKeyShort() throws SQLException {
        if (fetchKeys().next()) {
            return result.getShort(1);
        }
        throw noKeyException();
    }

    public void setParams(Param... params) throws SQLException {
        validateStatementNotNull();
        for (Param param : params) {
            if (param.getValue() instanceof String s) {
                statement.setString(param.getIndex(), s);
            } else if (param.getValue() instanceof Integer i) {
                statement.setInt(param.getIndex(), i);
            } else if (param.getValue() instanceof Long l) {
                statement.setLong(param.getIndex(), l);
            } else if (param.getValue() instanceof Double d) {
                statement.setDouble(param.getIndex(), d);
            } else if (param.getValue() instanceof LocalDate date) {
                statement.setDate(param.getIndex(), Date.valueOf(date));
            } else if (param.getValue() instanceof LocalDateTime dateTime) {
                statement.setTimestamp(param.getIndex(), Timestamp.valueOf(dateTime));
            } else if (param.getValue() instanceof LocalTime time) {
                statement.setTime(param.getIndex(), Time.valueOf(time));
            } else {
                throw new IllegalArgumentException(String.format("Invalid param type at index %d: %s", param.getIndex(), param.getValue().getClass().getName()));
            }
        }
    }

    @Override
    public void close() throws SQLException {
        if (result != null) result.close();
        if (statement != null) statement.close();
        if (connection != null) connection.close();
    }

    private void validateStatementNotNull() {
        if (statement == null) {
            throw new IllegalStateException("Statement is null");
        }
    }

    private IllegalStateException noKeyException() {
        return new IllegalStateException("No key generated");
    }
}
